### ISSUE TITLE
Not enough feedback when error

### ISSUE THREAD

**Issue by pzien** [elegantmonkeys/good-gcloud#1]
The only message when trying to log to gcloud:
There was a problem in _testreporter_ and it has been destroyed.

Can it be more descriptive?

**Comment by idosh** [comment]
The information depends on the data you supplied to the log function.
Please add your code so I'll be able to better understand it.

**Comment by pzien** [comment]
I'm trying to log http responses. I guess hapi is supplying the data to the log function. I also guess that there is some info missing in the gcloud options object but this is just a guess as the message doesn't say anything specific.

**Comment by idosh** [comment]
Please add your good reporters object, maybe there is something wrong there

**Comment by pzien** [comment]
I am sure that there is something wrong with my reporters object. The question is what. But it is actually good that is giving this mystic error. Closing the issue.

**Comment by idosh** [comment]
If you want I may help you with the reporters object
